name: build_server

on:
  push:
    branches: [ master ]
    paths: [ server/** ]
  workflow_dispatch:

defaults:
  run:
    working-directory: server

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
            pip3 install -r requirements.txt
            pip3 install cx_Freeze
      - name: Copy assets
        run: |
            Invoke-WebRequest -Uri https://home.in.tum.de/~zhangja/nornsvae/assets.zip -Outfile assets.zip
            Expand-Archive assets.zip .
      - name: Build
        run: python3 setup.py build
      - name: Package
        run: Compress-Archive build/* nornsvae_server_windows.zip
      - uses: actions/upload-artifact@v3
        with:
          name: nornsvae_server_windows
          path: server/nornsvae_server_windows.zip


  release:
    runs-on: ubuntu-latest
    needs: [build-windows]
    steps:
      - uses: actions/download-artifact@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Pre-release
          prerelease: true
          tag_name: release
          body: Test release (auto-generated)
          files: |
            nornsvae_server_windows/nornsvae_server_windows.zip
