name: build_server

on:
  push:
    branches: [ master ]
    paths: [ server/**, .github/** ]
  workflow_dispatch:

defaults:
  run:
    working-directory: server

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3    
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
            pip install -r requirements.txt
            pip install cx_Freeze
      - name: Copy assets
        run: |
            Invoke-WebRequest -Uri https://home.in.tum.de/~zhangja/nornsvae/assets.zip -Outfile assets.zip
            Expand-Archive assets.zip assets
      - name: Build
        run: python setup.py build
      - name: Package
        run: Compress-Archive build/* nornsvae_server_windows.zip
      - uses: actions/upload-artifact@v3
        with:
          name: nornsvae_server_windows
          path: server/nornsvae_server_windows.zip


  zip-source:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy assets
        run: |
            curl https://home.in.tum.de/~zhangja/nornsvae/assets.zip -o assets.zip
            mkdir assets
            unzip assets.zip -d assets
            rm assets.zip
            rm setup.py
      - name: Package
        run: zip -r nornsvae_server_source.zip .
      - uses: actions/upload-artifact@v3
        with:
          name: nornsvae_server_source
          path: server/nornsvae_server_source.zip


  release:
    runs-on: ubuntu-latest
    needs: [build-windows, zip-source]
    steps:
      - uses: actions/download-artifact@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Pre-release
          prerelease: true
          tag_name: release
          body: Test release (auto-generated)
          files: |
            nornsvae_server_windows/nornsvae_server_windows.zip
            nornsvae_server_source/nornsvae_server_source.zip
